nulsexplorer:
  url: https://testnet.nuls.world

nuls:
  chain_id: 261
  packing_node: True
  private_key: YOUR_PRIVATE_KEY_HERE

ethereum:
  enabled: True
  api_url: http://127.0.0.1:8545
  chain_id: 4
  packing_node: True
  private_key: YOUR_PRIVATE_KEY_HERE
  sync_contract: "0x608af68ed0789Fd93F9586A990B0C0429466Fd8A"
  start_height: 5042250

binancechain:
  enabled: True
  packing_node: True
  private_key: YOUR_PRIVATE_KEY_HERE
  sync_address: bnb1r3rf8cj9t2w6v0za3ufyp03as3nv6rjxteku6g
  start_time: "2019-05-22T00:00:00Z"

mongodb:
  uri: "mongodb://127.0.0.1"
  database: alephtest

ipfs:
  host: 127.0.0.1
  port: 5001
  gateway_port: 8080

aleph:
  queue_topic: ALEPH-TEST
