nulsexplorer:
  url: https://testnet.nuls.world

nuls:
  chain_id: 261
  packing_node: True
  private_key: YOUR_PRIVATE_KEY_HERE

ethereum:
  enabled: True
  api_url: http://127.0.0.1:8545
  chain_id: 4
  packing_node: True
  private_key: YOUR_PRIVATE_KEY_HERE
  sync_contract: "0xd1c53e2d39aA0D94E1738c926D439002c2016fb0"
  start_height: 4200000

mongodb:
  uri: "mongodb://127.0.0.1"
  database: alephtest

ipfs:
  host: 127.0.0.1
  port: 5001

aleph:
  queue_topic: ALEPH-TEST
