version: '2.4'

volumes:
  pyaleph-ipfs:
  pyaleph-mongodb:

services:
  pyaleph:
    restart: always
    image: alephim/pyaleph-node:beta
    command: pyaleph --config /opt/pyaleph/config.yml --very-verbose
    ports:
      - 8081:8080/tcp
      - 4024:4024/tcp
      - 4025:4025/tcp
    volumes:
      - ./config.yml:/opt/pyaleph/config.yml
      - ./node-secret.key:/opt/pyaleph/node-secret.key
    depends_on:
      - mongodb
      - ipfs
    networks:
      - pyaleph
    logging:
      options:
        max-size: 50m
#    Enable the following for debugging
#    stdin_open: true
#    tty: true

  ipfs:
    restart: always
    image: ipfs/go-ipfs
    ports:
      - 4001:4001
      - 4001:4001/udp
    volumes:
      - "pyaleph-ipfs:/data/ipfs"
    environment:
      - IPFS_PROFILE=server
    networks:
      - pyaleph
    command: ["daemon", "--enable-pubsub-experiment"]
    cpus: "0.3"
    mem_limit: 1500m

  mongodb:
    restart: always
    image: mongo:3.6
    volumes:
      - pyaleph-mongodb:/data/db
    command: mongod --storageEngine wiredTiger
    networks:
      - pyaleph
    cpus: "0.3"
    mem_limit: 500m

networks:
  pyaleph:
